name: Summarize new issues

on:
  issues:
    types: [opened]

jobs:
  summarize:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read

    steps:
      - name: Fetch issue details
        id: get_issue
        run: |
          echo "ISSUE_TITLE=${{ github.event.issue.title }}" >> $GITHUB_ENV
          echo "ISSUE_BODY=${{ github.event.issue.body }}" >> $GITHUB_ENV

      - name: Generate summary with OpenAI
        id: ai_summary
        run: |
          RESPONSE=$(curl -s https://api.openai.com/v1/chat/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
            -d '{
              "model": "gpt-4",
              "messages": [
                {
                  "role": "system",
                  "content": "Tu es un assistant GitHub. Résume l\'issue suivante en un seul paragraphe clair et précis, en français."
                },
                {
                  "role": "user",
                  "content": "Titre : '"${ISSUE_TITLE}"'\nCorps : '"${ISSUE_BODY}"'"
                }
              ]
            }' | jq -r '.choices[0].message.content')

          echo "summary=$RESPONSE" >> $GITHUB_OUTPUT

      - name: Comment with summary
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Titre : ${{ github.event.issue.title }}\n\nRésumé : ${{ steps.inference.outputs.response }}`
            })
