name: Summarize new issues

on:
  issues:
    types: [opened]

jobs:
  summarize:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read

    steps:
      - name: Préparer les variables d'issue
        run: |
          echo "ISSUE_TITLE=${{ github.event.issue.title }}" >> $GITHUB_ENV
          echo "ISSUE_BODY=${{ github.event.issue.body }}" >> $GITHUB_ENV

      - name: Générer le résumé avec OpenAI
        id: ai_summary
        run: |
          JSON=$(cat <<EOF
          {
            "model": "gpt-4",
            "messages": [
              {
                "role": "system",
                "content": "Tu es un assistant GitHub. Résume l'issue suivante en un seul paragraphe clair et précis, en français."
              },
              {
                "role": "user",
                "content": "Titre : ${ISSUE_TITLE}\nCorps : ${ISSUE_BODY}"
              }
            ]
          }
EOF
          )

          RESPONSE=$(curl -s https://api.openai.com/v1/chat/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
            -d "$JSON" | jq -r '.choices[0].message.content')

          echo "summary=$RESPONSE" >> $GITHUB_OUTPUT

      - name: Poster le résumé dans un commentaire
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🤖 **Résumé automatique :**\n\n${{ steps.ai_summary.outputs.summary }}`
            })
